language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "kgcorner-github"
    token:
      secure: "j+9nGOGGSVHtRTAtr6aqGEg27RTSU3AyqqLtiyGD1f5ExtZGS59xsIIvsWNmNx42nc5YU4oEAW6qN6Bn9+lp6W/99BYu+YjG6PL7MFbFe1ht8OHSZrwqXh4NevgFfV9pUbr/tu0A8taqhepZqvX7Lv/784pXsR/EYQWeSAcIrGxXY9RK/IhBUeQeWnTVQ+eCT8+EmxNsI2+tjmVaNBhsGb2lb9Dr1QKpTcxmOSYkfYahIBQ5EoWEAdo9U65wMYscVLiz2HWl6gGxS5w2S1Su1H91jSYXJPG6zhidpHSRPbf6D7kwYtAk/kXFf+HLut0QUmCLDdiO0o6y7VJn0Qf8T1bXqISOelELUUjthPgoZbzi6dgDbbOu6jVCoITt4lM40pXjqETo5FL0pOXsm7GM97UwDZfnLWv9rqDY8j471DBB7U7HY09N/YMyABrdm9wdO0z5xpu5DUiSQrv3BVloTkoVtULR8m4Il+BPVUVGFePuu5Vsoyu97CT7qEOiF4wefVswxTFOtCnfteneBuFWaPkoysGgS4Vrz0ngDLxP15JOokVrFXFSjomLlNkTRO4enp/5EwcivVqeV/lLdztBryH5Lnb+eGwoGR24NT37Ek/2nDI4BrBai3JDG3MUfHAvlYqnGQuefk1vJxlBqdEpK25JrwoKthTgxnNCeFWVOkI=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - cd backend
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_success:
  - bash <(curl -s https://codecov.io/bash)